// **IMPORTANT**
//Maintain redirects in alphabetical order, because it makes it easier to catch
//duplicated or conflicting redirects.
const redirector = new ThreeOhOneRedirector({
	legacyRedirects: [
		[
			/^\/v[0-1]\.[0-9]\/administration\/configuration/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/about-configuration/"
		],
		[
			/^\/v[0-1]\.[0-9]\/administration\/telemetry/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
		],
		[
			/^\/v[0-1]\.[0-9]\/api/,
			"https://docs.timescale.com/api/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/development/,
			"https://docs.timescale.com/timescaledb/latest/contributed-to-timescaledb/"
		],
		[
			/^\/v[0-1]\.[0-9]\/development\/contribute-to-docs/,
			"https://docs.timescale.com/timescaledb/latest/contributed-to-timescaledb/"
		],
		[
			/^\/v[0-1]\.[0-9]\/faq/,
			"https://docs.timescale.com/timescaledb/latest/overview/faq/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started/,
			"https://docs.timescale.com/getting-started/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/configuring/,
			"https://docs.timescale.com/timescaledb/latest/administration/configuration/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/creating-hypertables/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-cloud/,
			"https://docs.timescale.com/mst/latest/about-mst/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-cloud\/cloud-multi-node/,
			"https://docs.timescale.com/mst/latest/mst-multi-node/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge/,
			"https://https://docs.timescale.com/getting-started/latest/services/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-configuration/,
			"https://docs.timescale.com/cloud/latest/customize-configuration/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-multi-node/,
			"https://docs.timescale.com/cloud/latest/forge-multi-node/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-resize/,
			"https://docs.timescale.com/cloud/latest/scaling-a-service/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/install-psql-tutorial/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation-grafana/,
			"https://docs.timescale.com/tutorials/latest/grafana/installation/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation/,
			"https://docs.timescale.com/install/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/ami\/installation-ubuntu-ami/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/debian\/installation-apt-debian/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/debian\/installation-source/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/docker\/installation-docker/,
			"https://docs.timescale.com/install/latest/installation-docker/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/macos\/installation-homebrew/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/macos\/installation-source/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/rhel-centos\/installation-source/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/rhel-centos\/installation-yum/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/timescale-cloud\/installation-timescale-cloud/,
			"https://docs.timescale.com/install/latest/installation-mst/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/timescale-forge\/installation-timescale-forge/,
			"https://docs.timescale.com/install/latest/installation-cloud/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/ubuntu\/installation-apt-ubuntu/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/ubuntu\/installation-source/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/windows\/installation-source-windows/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-windows/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/installation\/windows\/installation-windows/,
			"https://docs.timescale.com/install/latest/self-hosted/installation-windows/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/migrating-data/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/setup-multi-node-basic/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/setup-multi-node-basic\/multi-node-self-managed/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
		],
		[
			/^\/v[0-1]\.[0-9]\/getting-started\/setup/,
			"https://docs.timescale.com/install/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction/,
			"https://docs.timescale.com/timescaledb/latest/overview/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction\/architecture/,
			"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction\/data-model/,
			"https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction\/time-series-data/,
			"https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction\/timescaledb-vs-nosql\//,
			"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/"
		],
		[
			/^\/v[0-1]\.[0-9]\/introduction\/timescaledb-vs-postgres/,
			"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/"
		],
		[
			/^\/v[0-1]\.[0-9]\/main/,
			"https://docs.timescale.com/timescaledb/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/release-notes/,
			"https://docs.timescale.com/timescaledb/latest/overview/release-notes/"
		],
		[
			/^\/v[0-1]\.[0-9]\/release-notes\/changes-in-timescaledb-2/,
			"https://docs.timescale.com/timescaledb/latest/overview/release-notes/changes-in-timescaledb-2/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials/,
			"https://docs.timescale.com/tutorials/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/clustering/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/continuous-aggs-tutorial/,
			"https://docs.timescale.com/getting-started/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale/,
			"https://promscale-legacy-docs.timescale.com/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\//,
			"https://promscale-legacy-docs.timescale.com/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-benefits/,
			"https://promscale-legacy-docs.timescale.com/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-how-it-works/,
			"https://promscale-legacy-docs.timescale.com/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-install/,
			"https://promscale-legacy-docs.timescale.com/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/other-sample-datasets/,
			"https://docs.timescale.com/tutorials/latest/sample-datasets/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/outflux/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/quickstart-go/,
			"https://docs.timescale.com/quick-start/latest/go/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/quickstart-node/,
			"https://docs.timescale.com/quick-start/latest/node/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/quickstart-python/,
			"https://docs.timescale.com/quick-start/latest/python/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/quickstart-ruby/,
			"https://docs.timescale.com/quick-start/latest/ruby/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/replication/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/telegraf-output-plugin/,
			"https://docs.timescale.com/tutorials/latest/telegraf-output-plugin"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-forecasting/,
			"https://docs.timescale.com/tutorials/latest/time-series-forecast/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-alerts/,
			"https://docs.timescale.com/tutorials/latest/grafana/setup-alerts/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-dashboards/,
			"https://docs.timescale.com/tutorials/latest/grafana/create-dashboard-and-panel/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-geospatial/,
			"https://docs.timescale.com/tutorials/latest/grafana/geospatial-dashboards/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-variables/,
			"https://docs.timescale.com/tutorials/latest/grafana/grafana-variables/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana/,
			"https://docs.timescale.com/tutorials/latest/grafana/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-hello-timescale/,
			"https://docs.timescale.com/getting-started/latest/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-monitor-django-prometheus/,
			"https://docs.timescale.com/tutorials/latest/howto-monitor-django-prometheus"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-simulate-iot-sensor-data/,
			"https://docs.timescale.com/tutorials/latest/simulate-iot-sensor-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-visualize-missing-data-grafana/,
			"https://docs.timescale.com/tutorials/latest/grafana/visualize-missing-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus/,
			"https://docs.timescale.com/tutorials/latest/setting-up-mst-for-prometheus/"
		],
		[
			/^\/v[0-1]\.[0-9]\/tutorials\/visualizing-time-series-data-in-tableau/,
			"https://docs.timescale.com/tutorials/latest/visualize-with-tableau/"
		],
		[
			/^\/v[0-1]\.[0-9]\/update-timescaledb/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
		],
		[
			/^\/v[0-1]\.[0-9]\/update-timescaledb\/update-docker/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/"
		],
		[
			/^\/v[0-1]\.[0-9]\/update-timescaledb\/update-tsdb-2/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/"
		],
		[
			/^\/v[0-1]\.[0-9]\/update-timescaledb\/upgrade-pg/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/actions/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/alerting/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/alerting"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/backup/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/compression/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/continuous-aggregates/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/data-retention/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/data-tiering/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/data-tiering/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/distributed-hypertables\//,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/hypertables/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/ingesting-data/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/limitations/,
			"https://docs.timescale.com/timescaledb/latest/overview/limitations/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/reading-data/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/schema-management/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/telemetry/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/tooling/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/tooling/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/troubleshooting/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/troubleshoot-timescaledb"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/visualizing-data/,
			"https://docs.timescale.com/tutorials/latest/grafana/"
		],
		[
			/^\/v[0-1]\.[0-9]\/using-timescaledb\/writing-data/,
			"https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/"
		]
	]
})
	.add(
		"/use-timescale/latest/popsql",
		"https://docs.timescale.com/getting-started/latest/run-queries-from-console/"
	)
	.add(
		"/ai/latest/pgvectorize",
		"https://docs.timescale.com/ai/latest/pgvectorizer"
	)
	.add(
		"/ai/latest/concepts",
		"https://docs.timescale.com/ai/latest/key-vector-database-concepts-for-understanding-pgvector/"
	)
	.add(
		"/ai/latest/langchain-integration",
		"https://docs.timescale.com/ai/latest/langchain-integration-for-pgvector-and-timescale-vector/"
	)
	.add(
		"/ai/latest/llamaindex-integration",
		"https://docs.timescale.com/ai/latest/llamaindex-integration-for-pgvector-and-timescale-vector/"
	)
	.add(
		"/ai/latest/python-interface",
		"https://docs.timescale.com/ai/latest/python-interface-for-pgvector-and-timescale-vector/"
	)
	.add(
		"/ai/latest/sql-interface",
		"https://docs.timescale.com/ai/latest/sql-interface-for-pgvector-and-timescale-vector/"
	)
	.add(
		"/administration/configuration",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/about-configuration/"
	)
	.add(
		"/administration/telemetry",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
	)
	.add("/api/api-timescaledb/", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add(
		"/api/data-retention/",
		"https://docs.timescale.com/api/latest/data-retention/"
	)
	.add(
		"/api/latest/analytics/",
		"https://docs.timescale.com/api/latest/hyperfunctions/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/api/latest/analytics/interpolate/",
		"https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/interpolate/"
	)
	.add(
		"/api/latest/analytics/locf/",
		"https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/locf/"
	)
	.add(
		"/api/latest/analytics/time_bucket_gapfill/",
		"https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/"
	)
	.add(
		"/api/latest/continuous-aggregates/",
		"https://docs.timescale.com/api/latest/continuous-aggregates/create_materialized_view/"
	)
	.add(
		"/api/latest/hyperfunctions/approx_count_distincts",
		"https://docs.timescale.com/api/latest/hyperfunctions/approximate-count-distinct/hyperloglog/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/counter_aggs/",
		"https://docs.timescale.com/api/latest/hyperfunctions/counters-and-gauges/counter_agg/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/downsample/",
		"https://docs.timescale.com/api/latest/hyperfunctions/downsampling",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/financial-analysis/ohlc/",
		"https://docs.timescale.com/api/latest/hyperfunctions/financial-analysis/candlestick_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/financial-analysis/open-high-low-close/",
		"https://docs.timescale.com/api/latest/hyperfunctions/financial-analysis/candlestick_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/financial-analysis/open-high-low-close-time/",
		"https://docs.timescale.com/api/latest/hyperfunctions/financial-analysis/candlestick_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/financial-analysis/rollup/",
		"https://docs.timescale.com/api/latest/hyperfunctions/financial-analysis/candlestick_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/",
		"https://docs.timescale.com/api/latest/hyperfunctions/frequency-analysis/freq_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/approx_count/",
		"https://docs.timescale.com/api/latest/hyperfunctions/frequency-analysis/count_min_sketch/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/duration_in",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/duration_in/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/interpolated_duration_in",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/interpolated_duration_in/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/into_values-state_agg",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/into_values-state_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/state_agg",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/state_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/frequency-analysis/topn_agg/",
		"https://docs.timescale.com/api/latest/hyperfunctions/frequency-analysis/freq_agg/#mcv_agg"
	)
	.add(
		"/api/latest/hyperfunctions/gapfilling-interpolation/",
		"https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/approx_percentile",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/approx_percentile_rank",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/error",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/max_val",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/mean",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/min_val",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/num_vals",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/num_vals-pct",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/percentile_agg",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/percentile-aggregation-methods",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/percentile-approximation/rollup-percentile",
		"https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/uddsketch/"
	)
	.add(
		"/api/latest/hyperfunctions/saturating_math/",
		"https://docs.timescale.com/api/latest/hyperfunctions/saturating-math/"
	)
	.add(
		"/api/latest/hyperfunctions/state-aggregates/",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-tracking/state_agg/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/state-tracking/timeline_agg",
		"https://docs.timescale.com/api/latest/hyperfunctions/state-tracking/state_agg/"
	)
	.add(
		"/api/latest/hyperfunctions/statistical-aggregates",
		"https://docs.timescale.com/api/latest/hyperfunctions/statistical-and-regression-analysis/stats_agg-one-variable",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/stats_aggs/",
		"https://docs.timescale.com/api/latest/hyperfunctions/statistical-and-regression-analysis/stats_agg-one-variable/",
		{ exact: false }
	)
	.add(
		"/api/latest/hyperfunctions/time-weighted-averages",
		"https://docs.timescale.com/api/latest/hyperfunctions/time-weighted-calculations/time_weight",
		{ exact: false }
	)
	.add("cloud", "https://docs.timescale.com/cloud/latest/")
	.add("/cloud/latest", "https://docs.timescale.com/use-timescale/latest/", {
		exact: false,
		appendPath: true
	})
	.add(
		"/cloud/latest/account-management",
		"https://docs.timescale.com/use-timescale/latest/billing/"
	)
	.add(
		"/cloud/latest/backup-restore-cloud.md/",
		"https://docs.timescale.com/use-timescale/latest/backup-restore-cloud/"
	)
	.add(
		"/cloud/latest/create-a-service",
		"https://docs.timescale.com/getting-started/latest/services/"
	)
	.add(
		"/cloud/latest/customize-configuration",
		"https://docs.timescale.com/use-timescale/latest/configuration/customize-configuration/"
	)
	.add(
		"/cloud/latest/disk-management",
		"https://docs.timescale.com/cloud/use-timescale/services/resources/"
	)
	.add(
		"/cloud/latest/explorer",
		"https://docs.timescale.com/use-timescale/latest/service-explorer/"
	)
	.add(
		"/cloud/latest/high-availability",
		"https://docs.timescale.com/use-timescale/latest/services/replicas/"
	)
	.add(
		"/cloud/latest/integrations",
		"https://docs.timescale.com/use-timescale/latest/metrics-logging/integrations/"
	)
	.add(
		"/cloud/latest/maintenance",
		"https://docs.timescale.com/use-timescale/latest/services/maintenance"
	)
	.add(
		"/cloud/latest/memory-management",
		"https://docs.timescale.com/use-timescale/latest/services/resources"
	)
	.add(
		"/cloud/latest/metrics",
		"https://docs.timescale.com/use-timescale/latest/metrics-logging/service-metrics/"
	)
	.add(
		"/cloud/latest/migrate-to-cloud",
		"https://docs.timescale.com/use-timescale/latest/migrate-db/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/cloud/latest/multi-factor-authentication",
		"https://docs.timescale.com/use-timescale/latest/security/multi-factor-authentication/"
	)
	.add(
		"/cloud/latest/operations",
		"https://docs.timescale.com/use-timescale/latest/configuration/"
	)
	.add(
		"/cloud/latest/postgresql-extensions",
		"https://docs.timescale.com/use-timescale/latest/services/postgresql-extensions/"
	)
	.add(
		"/cloud/latest/troubleshooting",
		"https://docs.timescale.com/keywords/troubleshooting/"
	)
	.add(
		"/cloud/latest/vpc-peering-aws/create/",
		"https://docs.timescale.com/use-timescale/latest/vpc/#complete-the-vpc-connection-in-aws"
	)
	.add(
		"/cloud/latest/scaling-a-service",
		"https://docs.timescale.com/use-timescale/latest/services/autoscaling"
	)
	.add(
		"/use-timescale/latest/services/create-a-service",
		"https://docs.timescale.com/getting-started/latest/services/"
	)
	.add(
		"/cloud/latest/service-explorer",
		"https://docs.timescale.com/use-timescale/latest/services/service-explorer/"
	)
	.add(
		"/cloud/latest/service-logs",
		"https://docs.timescale.com/use-timescale/latest/metrics-logging/service-logs/"
	)
	.add(
		"/cloud/latest/service-metrics",
		"https://docs.timescale.com/use-timescale/latest/metrics-logging/service-metrics/"
	)
	.add(
		"/cloud/latest/service-operations",
		"https://docs.timescale.com/use-timescale/latest/services/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/cloud/latest/service-operations/database-parameters",
		"https://docs.timescale.com/use-timescale/latest/configuration/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/cloud/latest/service-operations/high-availability",
		"https://docs.timescale.com/use-timescale/latest/services/replicas/"
	)
	.add(
		"/cloud/latest/service-operations/general",
		"https://docs.timescale.com/use-timescale/latest/services/"
	)
	.add(
		"/cloud/latest/service-operations/read-scaling",
		"https://docs.timescale.com/use-timescale/latest/services/replicas/"
	)
	.add(
		"/cloud/latest/service-operations/vpc",
		"https://docs.timescale.com/use-timescale/latest/vpc/"
	)
	.add(
		"/cloud/latest/service-overview/",
		"https://docs.timescale.com/use-timescale/latest/services/service-overview/"
	)
	.add(
		"/cloud/latest/service-settings/",
		"https://docs.timescale.com/use-timescale/latest/configuration/database-parameters/"
	)
	.add(
		"/cloud/latest/service-settings/customize-configuration",
		"https://docs.timescale.com/use-timescale/latest/configuration/customize-configuration/"
	)
	.add(
		"/cloud/latest/service-settings/settings-advanced",
		"https://docs.timescale.com/use-timescale/latest/configuration/advanced-parameters/"
	)
	.add(
		"/cloud/latest/user-management",
		"https://docs.timescale.com/use-timescale/latest/members/"
	)
	.add(
		"/cloud/latest/vpc-peering",
		"https://docs.timescale.com/use-timescale/latest/vpc/"
	)
	.add("/cloud-console/", "https://docs.timescale.com/console/")
	.add(
		"/clustering/getting-started/scaling-out/",
		"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
	)
	.add(
		"/clustering/introduction/architecture/",
		"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
	)
	.add(
		"/clustering/tutorials/clustering/",
		"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
	)
	.add(
		"development",
		"https://docs.timescale.com/timescaledb/latest/contribute-to-timescaledb/"
	)
	.add(
		"/development/contribute-to-docs",
		"https://docs.timescale.com/timescaledb/latest/contribute-to-docs/"
	)
	.add(
		"/distributed-hypertables/add_data_node/",
		"https://docs.timescale.com/api/latest/distributed-hypertables/add_data_node/"
	)
	.add("/faq", "https://docs.timescale.com/timescaledb/latest/overview/faq/")
	.add(
		"/forge/getting-started-forge/",
		"https://docs.timescale.com/getting-started/latest/services/"
	)
	.add("/forge", "https://docs.timescale.com/cloud/latest/")
	.add("/getting-started", "https://docs.timescale.com/getting-started/latest/")
	.add(
		"/getting-started/configuring",
		"https://docs.timescale.com/timescaledb/latest/administration/configuration/"
	)
	.add(
		"/getting-started/creating-hypertables",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
	)
	.add(
		"/getting-started/exploring-cloud",
		"https://docs.timescale.com/mst/latest/about-mst/"
	)
	.add(
		"/getting-started/exploring-cloud/cloud-multi-node",
		"https://docs.timescale.com/mst/latest/mst-multi-node/"
	)
	.add(
		"/getting-started/exploring-forge",
		"https://docs.timescale.com/getting-started/latest/services/"
	)
	.add(
		"/getting-started/exploring-forge/forge-configuration",
		"https://docs.timescale.com/cloud/latest/service-operations/database-parameters/"
	)
	.add(
		"/getting-started/exploring-forge/forge-multi-node",
		"https://docs.timescale.com/cloud/latest/cloud-multi-node/"
	)
	.add(
		"/getting-started/exploring-forge/forge-resize",
		"https://docs.timescale.com/cloud/latest/scaling-a-service/"
	)
	.add(
		"/getting-started/install-psql-tutorial",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/"
	)
	.add(
		"/getting-started/installation",
		"https://docs.timescale.com/install/latest/"
	)
	.add(
		"/getting-started/installation/ami/installation-ubuntu-ami",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/getting-started/installation/azure/installation-windows-azure",
		"https://docs.timescale.com/install/latest/installation-mst/"
	)
	.add(
		"/getting-started/installation/debian/installation-apt-debian",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/getting-started/installation/debian/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/getting-started/installation/docker/installation-docker",
		"https://docs.timescale.com/install/latest/installation-docker/"
	)
	.add(
		"/getting-started/installation/macos/installation-homebrew",
		"https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
	)
	.add(
		"/getting-started/installation/macos/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
	)
	.add(
		"/getting-started/installation/rhel-centos/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
	)
	.add(
		"/getting-started/installation/rhel-centos/installation-yum",
		"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
	)
	.add(
		"/getting-started/installation/timescale-cloud/installation-timescale-cloud",
		"https://docs.timescale.com/install/latest/installation-mst/"
	)
	.add(
		"/getting-started/installation/timescale-forge/installation-timescale-forge",
		"https://docs.timescale.com/install/latest/installation-cloud/"
	)
	.add(
		"/getting-started/installation/ubuntu/installation-apt-ubuntu",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/getting-started/installation/ubuntu/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/getting-started/installation/windows/",
		"https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
		{ exact: false }
	)
	.add(
		"/getting-started/installation-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/installation/"
	)
	.add(
		"/getting-started/latest/add-data/",
		"https://docs.timescale.com/getting-started/latest/time-series-data/"
	)
	.add(
		"/getting-started/latest/compress-data/",
		"https://docs.timescale.com/use-timescale/latest/compression/"
	)
	.add(
		"/getting-started/latest/create-cagg/",
		"https://docs.timescale.com/getting-started/latest/aggregation/",
		{ exact: false }
	)
	.add(
		"/getting-started/latest/create-hypertable/",
		"https://docs.timescale.com/getting-started/latest/tables/hypertables/"
	)
	.add(
		"/getting-started/latest/data-retention",
		"https://docs.timescale.com/use-timescale/latest/data-retention/"
	)
	.add(
		"/getting-started/latest/installation",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/getting-started/latest/installation/mac/installation-homebrew",
		"https://docs.timescale.com/self-hosted/latest/install/installation-macos/"
	)
	.add(
		"/getting-started/latest/query-data/",
		"https://docs.timescale.com/getting-started/latest/queries/"
	)
	.add(
		"/getting-started/migrating-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/"
	)
	.add("/getting-started/setup", "https://docs.timescale.com/install/latest/")
	.add(
		"/getting-started/setup-multi-node-basic",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
	)
	.add(
		"/getting-started/setup-multi-node-basic/multi-node-self-managed",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
	)
	.add(
		"/install/latest",
		"https://docs.timescale.com/self-hosted/latest/install/",
		{
			exact: false,
			appendPath: true
		}
	)
	.add(
		"/install/latest/installation-cloud",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/install/latest/installation-mst",
		"https://docs.timescale.com/mst/latest/installation-mst/"
	)
	.add(
		"/install/latest/self-hosted",
		"https://docs.timescale.com/self-hosted/latest/install",
		{
			exact: false,
			appendPath: true
		}
	)
	.add(
		"/install/latest/troubleshooting",
		"https://docs.timescale.com/self-hosted/latest/troubleshooting/"
	)
	.add(
		"/introduction",
		"https://docs.timescale.com/timescaledb/latest/overview/"
	)
	.add(
		"/introduction/architecture",
		"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/"
	)
	.add(
		"/introduction/data-model",
		"https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/"
	)
	.add(
		"/introduction/time-series-data",
		"https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/"
	)
	.add(
		"/introduction/timescaledb-vs-nosql/",
		"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/"
	)
	.add(
		"/introduction/timescaledb-vs-postgres",
		"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/"
	)
	.add("/latest/", "https://docs.timescale.com/timescaledb/latest/")
	.add(
		"/latest/administration/configuration",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/about-configuration"
	)
	.add(
		"/latest/administration/telemetry",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
	)
	.add("/latest/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add(
		"/latest/api/api-timescaledb/",
		"https://docs.timescale.com/api/latest/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/latest/development",
		"https://docs.timescale.com/timescaledb/latest/contribute-to-timescaledb/"
	)
	.add(
		"/latest/development/contribute-to-docs",
		"https://docs.timescale.com/timescaledb/latest/contribute-to-docs/"
	)
	.add(
		"/latest/faq",
		"https://docs.timescale.com/timescaledb/latest/overview/faq/",
		{ exact: false }
	)
	.add(
		"/latest/getting-started/",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/latest/getting-started/configuring",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/"
	)
	.add(
		"/latest/getting-started/create-hypertable/",
		"https://docs.timescale.com/getting-started/latest/create-hypertable/"
	)
	.add(
		"/latest/getting-started/creating-hypertables",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
	)
	.add(
		"/latest/getting-started/exploring-cloud",
		"https://docs.timescale.com/cloud/latest/customize-configuration/"
	)
	.add(
		"/latest/getting-started/exploring-cloud/cloud-multi-node",
		"https://docs.timescale.com/cloud/latest/customize-configuration/"
	)
	.add(
		"/latest/getting-started/exploring-forge",
		"https://docs.timescale.com/getting-started/latest/services/"
	)
	.add(
		"/latest/getting-started/exploring-forge/forge-multi-node",
		"https://docs.timescale.com/cloud/latest/cloud-multi-node/"
	)
	.add(
		"/latest/getting-started/exploring-forge/forge-resize",
		"https://docs.timescale.com/cloud/latest/scaling-a-service/"
	)
	.add(
		"/latest/getting-started/install-psql-tutorial",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/"
	)
	.add(
		"/latest/getting-started/installation",
		"https://docs.timescale.com/install/latest/"
	)
	.add(
		"/latest/getting-started/installation/debian/installation-apt-debian",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/latest/getting-started/installation/docker/installation-docker",
		"https://docs.timescale.com/install/latest/installation-docker/"
	)
	.add(
		"/latest/getting-started/installation/debian/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-source/"
	)
	.add(
		"/latest/getting-started/installation/docker/installation-docker",
		"https://docs.timescale.com/install/latest/installation-docker/"
	)
	.add(
		"/latest/getting-started/installation/mac/installation-homebrew",
		"https://docs.timescale.com/self-hosted/latest/install/installation-macos/"
	)
	.add(
		"/latest/getting-started/installation/macos/installation-homebrew",
		"https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
	)
	.add(
		"/latest/getting-started/installation/macos/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-source/"
	)
	.add(
		"/latest/getting-started/installation/rhel-centos/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
	)
	.add(
		"/latest/getting-started/installation/rhel-centos/installation-yum",
		"https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
	)
	.add(
		"/latest/getting-started/installation/timescale-cloud/",
		"https://docs.timescale.com/install/latest/installation-cloud/"
	)
	.add(
		"/latest/getting-started/installation/timescale-forge/installation-timescale-forge",
		"/install/latest/installation-cloud/"
	)
	.add(
		"/latest/getting-started/installation/ubuntu/installation-apt-ubuntu",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/latest/getting-started/installation/ubuntu/installation-source",
		"https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
	)
	.add(
		"/latest/getting-started/installation/windows/",
		"https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
		{ exact: false }
	)
	.add(
		"/latest/getting-started/installation-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/installation/"
	)
	.add(
		"/latest/getting-started/migrating-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/"
	)
	.add(
		"/latest/getting-started/setup-multi-node-basic",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/",
		{ exact: false }
	)
	.add(
		"/latest/getting-started/setup",
		"https://docs.timescale.com/install/latest/"
	)
	.add(
		"/latest/how-to-guides/compression/compression",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression"
	)
	.add(
		"/latest/how-to-guides/multi-node-setup/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/"
	)
	.add(
		"/latest/how-to-guides/psql-basics/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/about-psql/"
	)
	.add(
		"/latest/how-to-guides/replication-and-ha/replication/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/"
	)
	.add(
		"/latest/introduction",
		"https://docs.timescale.com/timescaledb/latest/overview/"
	)
	.add(
		"/latest/introduction/architecture",
		"https://docs.timescale.com/timescaledb/latest/overview/core-concepts/"
	)
	.add(
		"/latest/introduction/data-model",
		"https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/"
	)
	.add(
		"/latest/introduction/time-series-data",
		"https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/"
	)
	.add(
		"/latest/introduction/timescaledb-vs-nosql/",
		"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/"
	)
	.add(
		"/latest/introduction/timescaledb-vs-postgres",
		"https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/"
	)
	.add("/latest/main", "https://docs.timescale.com/timescaledb/latest/")
	.add(
		"/latest/release-notes",
		"https://docs.timescale.com/timescaledb/latest/overview/release-notes/"
	)
	.add(
		"/latest/release-notes/changes-in-timescaledb-2",
		"https://docs.timescale.com/timescaledb/latest/overview/release-notes/changes-in-timescaledb-2/"
	)
	.add("/latest/tutorials", "https://docs.timescale.com/tutorials/latest/")
	.add(
		"/latest/tutorials/analyze-cryptocurrency-data",
		"https://docs.timescale.com/tutorials/latest/analyze-cryptocurrency-data/"
	)
	.add(
		"/latest/tutorials/clustering",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
	)
	.add(
		"/latest/tutorials/continuous-aggs-tutorial",
		"https://docs.timescale.com/getting-started/latest/create-cagg/"
	)
	.add(
		"/latest/tutorials/getting-started-with-promscale",
		"https://promscale-legacy-docs.timescale.com/",
		{ exact: false }
	)
	.add(
		"/latest/tutorials/other-sample-datasets",
		"https://docs.timescale.com/tutorials/latest/sample-datasets/"
	)
	.add(
		"/latest/tutorials/outflux",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/"
	)
	.add(
		"/latest/tutorials/quickstart-go/",
		"https://docs.timescale.com/timescaledb/latest/quick-start/golang/"
	)
	.add(
		"/latest/tutorials/quickstart-node",
		"https://docs.timescale.com/quick-start/latest/node/"
	)
	.add(
		"/latest/tutorials/quickstart-node/",
		"https://docs.timescale.com/timescaledb/latest/quick-start/node/"
	)
	.add(
		"/latest/tutorials/quickstart-python",
		"https://docs.timescale.com/quick-start/latest/python/"
	)
	.add(
		"/latest/tutorials/quickstart-python/",
		"https://docs.timescale.com/timescaledb/latest/quick-start/python/"
	)
	.add(
		"/latest/tutorials/quickstart-ruby",
		"https://docs.timescale.com/quick-start/latest/ruby/"
	)
	.add(
		"/latest/tutorials/prometheus-adapter/",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/latest/tutorials/replication",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/"
	)
	.add(
		"/latest/tutorials/telegraf-output-plugin",
		"https://docs.timescale.com/tutorials/latest/telegraf-output-plugin"
	)
	.add(
		"/latest/tutorials/tutorial-forecasting",
		"https://docs.timescale.com/tutorials/latest/time-series-forecast/"
	)
	.add(
		"/latest/tutorials/tutorial-grafana-alerts",
		"https://docs.timescale.com/tutorials/latest/grafana/setup-alerts/"
	)
	.add(
		"/latest/tutorials/tutorial-grafana-dashboards",
		"https://docs.timescale.com/tutorials/latest/grafana/create-dashboard-and-panel/"
	)
	.add(
		"^/latest/tutorials/tutorial-grafana-geospatial",
		"https://docs.timescale.com/tutorials/latest/grafana/geospatial-dashboards/"
	)
	.add(
		"/latest/tutorials/tutorial-grafana-variables",
		"https://docs.timescale.com/tutorials/latest/grafana/grafana-variables/"
	)
	.add(
		"/latest/tutorials/tutorial-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/"
	)
	.add(
		"/latest/tutorials/tutorial-hello-nyc",
		"https://docs.timescale.com/tutorials/latest/nyc-taxi-cab/"
	)
	.add(
		"/latest/tutorials/tutorial-hello-timescale",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/latest/tutorials/tutorial-howto-monitor-django-prometheus",
		"https://docs.timescale.com/tutorials/latest/howto-monitor-django-prometheus"
	)
	.add(
		"/latest/tutorials/tutorial-howto-simulate-iot-sensor-data",
		"https://docs.timescale.com/tutorials/latest/simulate-iot-sensor-data/"
	)
	.add(
		"/latest/tutorials/tutorial-howto-visualize-missing-data-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/visualize-missing-data/"
	)
	.add(
		"/latest/tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus",
		"https://docs.timescale.com/tutorials/latest/monitor-mst-with-prometheus/"
	)
	.add(
		"/latest/tutorials/tutorial-setup-timescale-prometheus/",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/latest/tutorials/tutorial-use-timescale-prometheus-grafana/",
		"https://docs.timescale.com/tutorials/latest/grafana/"
	)
	.add(
		"/latest/tutorials/visualizing-time-series-data-in-tableau",
		"https://docs.timescale.com/tutorials/latest/visualize-with-tableau/"
	)
	.add(
		"/latest/update-timescaledb",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
	)
	.add(
		"/latest/update-timescaledb/update-docker",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/"
	)
	.add(
		"/latest/update-timescaledb/update-tsdb-2",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/"
	)
	.add(
		"/latest/update-timescaledb/upgrade-pg",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/"
	)
	.add(
		"/latest/using-timescaledb",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/latest/using-timescaledb/actions",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/"
	)
	.add(
		"/latest/using-timescaledb/backup",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/"
	)
	.add(
		"/latest/using-timescaledb/ingesting-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/"
	)
	.add(
		"/latest/using-timescaledb/limitations",
		"https://docs.timescale.com/timescaledb/latest/overview/limitations/"
	)
	.add(
		"/latest/using-timescaledb/reading-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/"
	)
	.add(
		"/latest/using-timescaledb/telemetry",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
	)
	.add(
		"/latest/using-timescaledb/update-db/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
	)
	.add(
		"/latest/using-timescaledb/visualizing-data",
		"https://docs.timescale.com/tutorials/latest/grafana/"
	)
	.add(
		"/latest/using-timescaledb/writing-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/"
	)
	.add("/main", "https://docs.timescale.com/timescaledb/latest/")
	.add(
		"/mst/latest/create-a-service",
		"https://docs.timescale.com/mst/latest/about-mst"
	)
	.add("/mst", "https://docs.timescale.com/mst/latest/")
	.add("/promscale", "https://promscale-legacy-docs.timescale.com/", {
		exact: false
	})
	.add(
		"/quick-start/latest/dotnet/",
		"https://docs.timescale.com/quick-start/latest/"
	)
	.add(
		"/release-notes",
		"https://docs.timescale.com/timescaledb/latest/overview/release-notes/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/self-hosted/latest/install/installation-redhat",
		"https://docs.timescale.com/self-hosted/latest/install/installation-linux/"
	)
	.add(
		"/self-hosted/latest/self-hosted/backup-and-restore/troubleshooting/",
		"https://docs.timescale.com/self-hosted/latest/troubleshooting/"
	)
	.add("/timescale-cloud", "https://docs.timescale.com/mst/latest/", {
		exact: false
	})
	.add("/timescale-forge", "https://docs.timescale.com/cloud/latest/", {
		exact: false
	})
	.add("/timescale-forge/latest", "https://docs.timescale.com/cloud/latest/")
	.add("/timescaledb/", "https://docs.timescale.com/use-timescale/latest/")
	.add(
		"/timescaledb/latest/",
		"https://docs.timescale.com/use-timescale/latest/"
	)
	.add("/timescaledb/latest/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add(
		"/timescaledb/latest/contribute-to-docs",
		"https://docs.timescale.com/about/latest/contribute-to-docs/"
	)
	.add(
		"/timescaledb/latest/contribute-to-timescaledb",
		"https://docs.timescale.com/about/latest/contribute-to-timescale/"
	)
	.add(
		"/timescaledb/latest/getting-started/",
		"https://docs.timescale.com/getting-started/latest/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/how-to-guides",
		"https://docs.timescale.com/use-timescale/latest/",
		{
			exact: false,
			appendPath: true
		}
	)
	.add(
		"/timescaledb/latest/how-to-guides/backup-and-restore/docker-and-wale",
		"https://docs.timescale.com/self-hosted/latest/backup-and-restore/docker-and-wale"
	)
	.add(
		"/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore",
		"https://docs.timescale.com/self-hosted/latest/backup-and-restore/pg-dump-and-restore"
	)
	.add(
		"/timescaledb/latest/how-to-guides/backup-and-restore/physical",
		"https://docs.timescale.com/self-hosted/latest/backup-and-restore/physical/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/backup-and-restore/troubleshooting",
		"https://docs.timescale.com/self-hosted/latest/troubleshooting"
	)
	.add(
		"/timescaledb/latest/how-to-guides/compression/compression-basics/",
		"https://docs.timescale.com/use-timescale/latest/how-to-guides/compression/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/configuration/docker-config",
		"https://docs.timescale.com/self-hosted/latest/configuration/docker-config/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/configuration/postgres-config",
		"https://docs.timescale.com/self-hosted/latest/configuration/postgres-config/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/configuration/telemetry",
		"https://docs.timescale.com/self-hosted/latest/configuration/telemetry/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/configuration/timescaledb-config",
		"https://docs.timescale.com/self-hosted/latest/configuration/timescaledb-config/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/configuration/timescaledb-tune",
		"https://docs.timescale.com/self-hosted/latest/configuration/timescaledb-tune"
	)
	.add(
		"/timescaledb/latest/how-to-guides/continuous-aggregates/adding-automatic-refresh-policies/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/data-tiering",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/manage-storage/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/hypertables/best-practices",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables/#best-practices-for-time-partitioning"
	)
	.add(
		"/timescaledb/latest/how-to-guides/hypertables/distributed-hypertables",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/install-timescaledb-toolkit/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/install-timescaledb/",
		"https://docs.timescale.com/install/latest/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/multi-node-setup/",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/multinode-timescaledb",
		"https://docs.timescale.com/self-hosted/latest/multinode-timescaledb/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/how-to-guides/replication-and-ha",
		"https://docs.timescale.com/self-hosted/latest/replication-and-ha/",
		{ exact: false }
	)
	.add(
		"/timescaledb/latest/how-to-guides/tooling",
		"https://docs.timescale.com/self-hosted/latest/tooling/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/how-to-guides/troubleshoot-timescaledb",
		"https://docs.timescale.com/self-hosted/latest/troubleshooting/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/upgrades",
		"https://docs.timescale.com/self-hosted/latest/upgrades/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/how-to-guides/upgrades/troubleshooting",
		"https://docs.timescale.com/self-hosted/latest/troubleshooting/"
	)
	.add(
		"/timescaledb/latest/how-to-guides/uninstall",
		"https://docs.timescale.com/self-hosted/latest/uninstall",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/introduction",
		"https://docs.timescale.com/use-timescale/latest/"
	)
	.add(
		"/timescaledb/latest/overview",
		"https://docs.timescale.com/use-timescale/latest/"
	)
	.add(
		"/timescaledb/latest/overview/what-is-time-series-data",
		"https://docs.timescale.com/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/backup-restore",
		"https://docs.timescale.com/use-timescale/latest/backup-restore-cloud/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/compression",
		"https://docs.timescale.com/use-timescale/latest/compression/",
		{ exact: false }
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/continuous-aggregates",
		"https://docs.timescale.com/use-timescale/latest/continuous-aggregates/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/data-retention",
		"https://docs.timescale.com/use-timescale/latest/data-retention/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/distributed-hypertables",
		"https://docs.timescale.com/use-timescale/latest/distributed-hypertables/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/hypertables-and-chunks",
		"https://docs.timescale.com/use-timescale/latest/hypertables/about-hypertables",
		{ exact: false }
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/scaling",
		"https://docs.timescale.com/use-timescale/latest/services/autoscaling/"
	)
	.add(
		"/timescaledb/latest/overview/core-concepts/user-defined-actions",
		"https://docs.timescale.com/use-timescale/latest/user-defined-actions/"
	)
	.add(
		"/timescaledb/latest/overview/deployment-options",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/timescaledb/latest/overview/faq",
		"https://docs.timescale.com/about/latest/",
		{ exact: false }
	)
	.add(
		"/timescaledb/latest/overview/faq/using-timescaledb",
		"https://docs.timescale.com/use-timescale/latest/"
	)
	.add(
		"/timescaledb/latest/overview/kubernetes",
		"https://docs.timescale.com/self-hosted/latest/install/installation-kubernetes"
	)
	.add(
		"/timescaledb/latest/overview/limitations",
		"https://docs.timescale.com/use-timescale/latest/limitations/"
	)
	.add(
		"/timescaledb/latest/overview/release-notes",
		"https://docs.timescale.com/about/latest/release-notes/"
	)
	.add(
		"/timescaledb/latest/overview/release-notes/changes-in-timescaledb-2/",
		"https://docs.timescale.com/about/latest/release-notes/changes-in-timescaledb-2/"
	)
	.add(
		"/timescaledb/latest/quick-start",
		"https://docs.timescale.com/quick-start/latest/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/release-notes/changes-in-timescaledb-2/",
		"https://docs.timescale.com/about/latest/release-notes/changes-in-timescaledb-2/"
	)
	.add(
		"/timescaledb/latest/timescaledb-edition-comparison",
		"https://docs.timescale.com/about/latest/timescaledb-editions/"
	)
	.add(
		"/timescaledb/latest/tutorials",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/timescaledb/latest/tutorials/financial-candlestick-tick-data/",
		"https://docs.timescale.com/tutorials/latest/financial-tick-data/"
	)
	.add(
		"/timescaledb/latest/tutorials/howto-monitor-django-prometheus",
		"https://docs.timescale.com/tutorials/latest/monitor-django-with-prometheus/"
	)
	.add(
		"/timescaledb/latest/tutorials/promscale/",
		"https://promscale-legacy-docs.timescale.com/"
	)
	.add(
		"/timescaledb/latest/tutorials/setting-up-mst-endpoint-for-prometheus/",
		"https://docs.timescale.com/tutorials/latest/monitor-mst-with-prometheus/"
	)
	.add(
		"/timescaledb/latest/tutorials/visualize-with-tableu/",
		"https://docs.timescale.com/tutorials/latest/visualize-with-tableau/"
	)
	.add(
		"/timescaledb/latest/update-timescaledb/update-tsdb-2",
		"https://docs.timescale.com/self-hosted/latest/upgrades/"
	)
	.add(
		"/timescaledb/latest/using-timescaledb/actions",
		"https://docs.timescale.com/use-timescale/latest/user-defined-actions/"
	)
	.add(
		"/timescaledb/latest/using-timescaledb/distributed-hypertables",
		"https://docs.timescale.com/use-timescale/latest/distributed-hypertables/"
	)
	.add(
		"/timescaledb/latest/using-timescaledb/telemetry",
		"https://docs.timescale.com/self-hosted/latest/configuration/telemetry/"
	)
	.add(
		"/tutorials/clustering",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
	)
	.add(
		"/tutorials/continuous-aggs-tutorial",
		"https://docs.timescale.com/getting-started/latest/create-cagg/"
	)
	.add(
		"/tutorials/getting-started-with-promscale",
		"https://promscale-legacy-docs.timescale.com/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/analyze-cryptocurrency-data/",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/tutorials/latest/analyze-intraday-stocks/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/aws-lambda/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/financial-candlestick-tick-data/create-candlestick-aggregates/",
		"https://docs.timescale.com/tutorials/latest/financial-tick-data/financial-tick-query/"
	)
	.add(
		"/tutorials/latest/grafana/",
		"https://docs.timescale.com/use-timescale/latest/integrations/observability-alerting/grafana/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/howto-monitor-django-prometheus",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/tutorials/latest/ingest-real-time-web-socket-data/",
		"https://docs.timescale.com/tutorials/latest/ingest-real-time-websocket-data/"
	)
	.add(
		"/tutorials/latest/monitor-mst-with-prometheus/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/nfl-analytics/",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/tutorials/latest/prometheus-adapter/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/sample-datasets/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/other-sample-datasets",
		"https://docs.timescale.com/tutorials/latest/sample-datasets/"
	)
	.add(
		"/tutorials/latest/simulate-iot-sensor-data",
		"https://docs.timescale.com/tutorials/latest/"
	)
	.add(
		"/tutorials/latest/telegraf-output-plugin/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/latest/time-series-forecast/",
		"https://docs.timescale.com/tutorials/latest/",
		{ exact: false }
	)
	.add(
		"/tutorials/outflux",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/"
	)
	.add(
		"/tutorials/quickstart-go",
		"https://docs.timescale.com/timescaledb/latest/quick-start/golang/"
	)
	.add(
		"/tutorials/quickstart-node",
		"https://docs.timescale.com/timescaledb/latest/quick-start/node/"
	)
	.add(
		"/tutorials/quickstart-python",
		"https://docs.timescale.com/timescaledb/latest/quick-start/python/"
	)
	.add(
		"/tutorials/quickstart-ruby",
		"https://docs.timescale.com/timescaledb/latest/quick-start/ruby/"
	)
	.add(
		"/tutorials/replication",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/"
	)
	.add(
		"/tutorials/telegraf-output-plugin",
		"https://docs.timescale.com/tutorials/latest/telegraf-output-plugin"
	)
	.add(
		"/tutorials/tutorial-forecasting",
		"https://docs.timescale.com/tutorials/latest/time-series-forecast/"
	)
	.add(
		"^/tutorials/tutorial-grafana-alerts",
		"https://docs.timescale.com/tutorials/latest/grafana/setup-alerts/"
	)
	.add(
		"/tutorials/tutorial-grafana-dashboards",
		"https://docs.timescale.com/tutorials/latest/grafana/create-dashboard-and-panel/"
	)
	.add(
		"/tutorials/tutorial-grafana-geospatial",
		"https://docs.timescale.com/tutorials/latest/grafana/geospatial-dashboards/"
	)
	.add(
		"/tutorials/tutorial-grafana-variables",
		"https://docs.timescale.com/tutorials/latest/grafana/grafana-variables/"
	)
	.add(
		"/tutorials/tutorial-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/"
	)
	.add(
		"/tutorials/tutorial-hello-timescale",
		"https://docs.timescale.com/getting-started/latest/"
	)
	.add(
		"/tutorials/tutorial-howto-monitor-django-prometheus",
		"https://docs.timescale.com/tutorials/latest/howto-monitor-django-prometheus"
	)
	.add(
		"/tutorials/tutorial-howto-simulate-iot-sensor-data",
		"https://docs.timescale.com/tutorials/latest/simulate-iot-sensor-data/"
	)
	.add(
		"/tutorials/tutorial-howto-visualize-missing-data-grafana",
		"https://docs.timescale.com/tutorials/latest/grafana/visualize-missing-data/"
	)
	.add(
		"/tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus",
		"https://docs.timescale.com/tutorials/latest/setting-up-mst-for-prometheus/"
	)
	.add(
		"/tutorials/visualizing-time-series-data-in-tableau",
		"https://docs.timescale.com/tutorials/latest/visualize-with-tableau/"
	)
	.add("/tutorials", "https://docs.timescale.com/tutorials/latest/")
	.add(
		"/update-timescaledb",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
	)
	.add(
		"/update-timescaledb/update-docker",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/"
	)
	.add(
		"/update-timescaledb/update-tsdb-2",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/"
	)
	.add(
		"/update-timescaledb/upgrade-pg",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/"
	)
	.add(
		"/use-timescale/latest/backup-and-restore/",
		"https://docs.timescale.com/use-timescale/latest/backup-restore-cloud/"
	)
	.add(
		"/use-timescale/latest/compression/about-compression",
		"https://docs.timescale.com/use-timescale/latest/compression"
	)
	.add(
		"/use-timescale/latest/connecting/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/"
	)
	.add(
		"/use-timescale/latest/connecting/about-connecting",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/about-connecting/"
	)
	.add(
		"/use-timescale/latest/connecting/about-psql/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/about-psql/"
	)
	.add(
		"/use-timescale/latest/connecting/dbeaver/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/dbeaver/"
	)
	.add(
		"/use-timescale/latest/connecting/pgadmin/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/"
	)
	.add(
		"/use-timescale/latest/connecting/psql/",
		"https://docs.timescale.com/use-timescale/latest/integrations/query-admin/about-psql/"
	)
	.add(
		"/use-timescale/latest/data-tiering/move-data/",
		"https://docs.timescale.com/use-timescale/latest/data-tiering/tier-data-object-storage/"
	)
	.add(
		"/use-timescale/latest/how-to-guides/compression/",
		"https://docs.timescale.com/use-timescale/latest/compression/"
	)
	.add(
		"/use-timescale/latest/hyperfunctions/install-toolkit/",
		"https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/"
	)
	.add(
		"/use-timescale/latest/ingest-data/ingest-telegraf",
		"https://docs.timescale.com/use-timescale/latest/integrations/data-ingest/telegraf/"
	)
	.add(
		"/use-timescale/latest/install-timescaledb/self-hosted/",
		"https://docs.timescale.com/self-hosted/latest/install/"
	)
	.add(
		"/use-timescale/latest/install-timescaledb-toolkit/",
		"https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/"
	)
	.add(
		"/use-timescale/latest/migrate-data/",
		"https://docs.timescale.com/use-timescale/latest/migration/",
		{ exact: false }
	)
	.add(
		"/use-timescale/latest/migrate-db/",
		"https://docs.timescale.com/use-timescale/latest/migration/",
		{ exact: false }
	)
	.add(
		"/use-timescale/latest/postgresql-extensions/",
		"https://docs.timescale.com/use-timescale/latest/extensions/"
	)
	.add(
		"/use-timescale/latest/schema-management/manage-storage/",
		"https://docs.timescale.com/use-timescale/latest/schema-management/"
	)
	.add(
		"/use-timescale/latest/services/autoscaling",
		"https://docs.timescale.com/use-timescale/latest/resources/autoscaling/"
	)
	.add(
		"/use-timescale/latest/services/maintenance",
		"https://docs.timescale.com/use-timescale/latest/upgrades/"
	)
	.add(
		"/use-timescale/latest/services/postgresql-extensions",
		"https://docs.timescale.com/use-timescale/latest/extensions/"
	)
	.add(
		"/use-timescale/latest/services/regions",
		"https://docs.timescale.com/use-timescale/latest/regions/"
	)
	.add(
		"/use-timescale/latest/services/replicas/",
		"https://docs.timescale.com/use-timescale/latest/ha-replicas/"
	)
	.add(
		"/use-timescale/latest/services/resources/",
		"https://docs.timescale.com/use-timescale/latest/resources/"
	)
	.add(
		"/use-timescale/latest/update-timescaledb/",
		"https://docs.timescale.com/self-hosted/latest/upgrades/",
		{ exact: false }
	)
	.add(
		"/use-timescale/latest/vpc-peering-aws/",
		"https://docs.timescale.com/use-timescale/latest/vpc/"
	)
	.add(
		"/using-timescaledb",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/",
		{ exact: false, appendPath: true }
	)
	.add(
		"/using-timescaledb/actions",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/"
	)
	.add(
		"/using-timescaledb/backup",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/"
	)
	.add(
		"/using-timescaledb/ingesting-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/"
	)
	.add(
		"/using-timescaledb/limitations",
		"https://docs.timescale.com/timescaledb/latest/overview/limitations/"
	)
	.add(
		"/using-timescaledb/reading-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/"
	)
	.add(
		"/using-timescaledb/telemetry",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
	)
	.add(
		"/using-timescaledb/troubleshooting",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/troubleshoot-timescaledb"
	)
	.add(
		"/using-timescaledb/update-db",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
	)
	.add(
		"/using-timescaledb/visualizing-data",
		"https://docs.timescale.com/tutorials/latest/grafana/"
	)
	.add(
		"/using-timescaledb/writing-data",
		"https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/"
	)
	.add("/v0.8/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.8/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.9/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.9/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.10/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.10/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.11/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.11/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.12/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v0.12/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v2.0/", "https://docs.timescale.com/timescaledb/latest/", {
		exact: false,
		appendPath: true
	})
	.add("/v2.0/api", "https://docs.timescale.com/api/latest/", {
		exact: false,
		appendPath: true
	});
