// **IMPORTANT**
//Maintain redirects in alphabetical order, because it makes it easier to catch
//duplicated or conflicting redirects.
const redirector = new ThreeOhOneRedirector({
  legacyRedirects: [
    [
      /^\/v[0-1]\.[0-9]\/administration\/configuration/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/about-configuration/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/administration\/telemetry/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/",
    ],
    [/^\/v[0-1]\.[0-9]\/api/, "https://docs.timescale.com/api/latest/"],
    [
      /^\/v[0-1]\.[0-9]\/development/,
      "https://docs.timescale.com/timescaledb/latest/contributed-to-timescaledb/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/development\/contribute-to-docs/,
      "https://docs.timescale.com/timescaledb/latest/contributed-to-timescaledb/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/faq/,
      "https://docs.timescale.com/timescaledb/latest/overview/faq/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started/,
      "https://docs.timescale.com/getting-started/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/configuring/,
      "https://docs.timescale.com/timescaledb/latest/administration/configuration/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/creating-hypertables/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-cloud/,
      "https://docs.timescale.com/mst/latest/about-mst/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-cloud\/cloud-multi-node/,
      "https://docs.timescale.com/mst/latest/mst-multi-node/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge/,
      "https://docs.timescale.com/cloud/latest/create-a-service/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-configuration/,
      "https://docs.timescale.com/cloud/latest/customize-configuration/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-multi-node/,
      "https://docs.timescale.com/cloud/latest/forge-multi-node/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/exploring-forge\/forge-resize/,
      "https://docs.timescale.com/cloud/latest/scaling-a-service/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/install-psql-tutorial/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation-grafana/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/installation/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation/,
      "https://docs.timescale.com/install/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/ami\/installation-ubuntu-ami/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-debian/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/debian\/installation-apt-debian/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-debian/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/debian\/installation-source/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-debian/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/docker\/installation-docker/,
      "https://docs.timescale.com/install/latest/installation-docker/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/macos\/installation-homebrew/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-macos/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/macos\/installation-source/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-macos/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/rhel-centos\/installation-source/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/rhel-centos\/installation-yum/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/timescale-cloud\/installation-timescale-cloud/,
      "https://docs.timescale.com/install/latest/installation-mst/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/timescale-forge\/installation-timescale-forge/,
      "https://docs.timescale.com/install/latest/installation-cloud/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/ubuntu\/installation-apt-ubuntu/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-debian/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/ubuntu\/installation-source/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-debian/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/windows\/installation-source-windows/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/installation\/windows\/installation-windows/,
      "https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/migrating-data/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/setup-multi-node-basic/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/setup-multi-node-basic\/multi-node-self-managed/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/getting-started\/setup/,
      "https://docs.timescale.com/install/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction/,
      "https://docs.timescale.com/timescaledb/latest/overview/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction\/architecture/,
      "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction\/data-model/,
      "https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction\/time-series-data/,
      "https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction\/timescaledb-vs-nosql\//,
      "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/introduction\/timescaledb-vs-postgres/,
      "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/main/,
      "https://docs.timescale.com/timescaledb/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/release-notes/,
      "https://docs.timescale.com/timescaledb/latest/overview/release-notes/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/release-notes\/changes-in-timescaledb-2/,
      "https://docs.timescale.com/timescaledb/latest/overview/release-notes/changes-in-timescaledb-2/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/clustering/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/continuous-aggs-tutorial/,
      "https://docs.timescale.com/getting-started/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale/,
      "https://docs.timescale.com/promscale/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\//,
      "https://docs.timescale.com/promscale/latest/query-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-benefits/,
      "https://docs.timescale.com/promscale/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-how-it-works/,
      "https://docs.timescale.com/promscale/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/getting-started-with-promscale\/promscale-install/,
      "https://docs.timescale.com/promscale/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/other-sample-datasets/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/sample-datasets/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/outflux/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/quickstart-go/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/go/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/quickstart-node/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/node/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/quickstart-python/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/python/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/quickstart-ruby/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/ruby/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/replication/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/telegraf-output-plugin/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/telegraf-output-plugin",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-forecasting/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/time-series-forecast/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-alerts/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/setup-alerts/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-dashboards/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/create-dashboard-and-panel/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-geospatial/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/geospatial-dashboards/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana-variables/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/grafana-variables/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-grafana/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-hello-timescale/,
      "https://docs.timescale.com/getting-started/latest/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-monitor-django-prometheus/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/howto-monitor-django-prometheus",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-simulate-iot-sensor-data/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/simulate-iot-sensor-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-howto-visualize-missing-data-grafana/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/visualize-missing-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/setting-up-mst-for-prometheus/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/tutorials\/visualizing-time-series-data-in-tableau/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/visualize-with-tableau/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/update-timescaledb/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/update-timescaledb\/update-docker/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/update-timescaledb\/update-tsdb-2/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/update-timescaledb\/upgrade-pg/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/actions/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/alerting/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/alerting",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/backup/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/compression/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/continuous-aggregates/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/data-retention/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/data-tiering/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/data-tiering/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/distributed-hypertables\//,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/hypertables/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/ingesting-data/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/limitations/,
      "https://docs.timescale.com/timescaledb/latest/overview/limitations/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/reading-data/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/schema-management/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/telemetry/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/tooling/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/tooling/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/troubleshooting/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/troubleshoot-timescaledb",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/visualizing-data/,
      "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/",
    ],
    [
      /^\/v[0-1]\.[0-9]\/using-timescaledb\/writing-data/,
      "https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/",
    ],
  ],
})
  .add(
    "/administration/configuration",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/about-configuration/"
  )
  .add(
    "/administration/telemetry",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
  )
  .add("/api/api-timescaledb/", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add(
    "/api/data-retention/",
    "https://docs.timescale.com/api/latest/data-retention/"
  )
  .add(
    "/api/latest/analytics/",
    "https://docs.timescale.com/api/latest/hyperfunctions/",
    { exact: false, appendPath: true }
  )
  .add(
    "/api/latest/analytics/interpolate/",
    "https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/interpolate/"
  )
  .add(
    "/api/latest/analytics/locf/",
    "https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/locf/"
  )
  .add(
    "/api/latest/analytics/time_bucket_gapfill/",
    "https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/"
  )
  .add(
    "/api/latest/hyperfunctions/approx_count_distincts",
    "https://docs.timescale.com/api/latest/hyperfunctions/approximate-count-distinct/hyperloglog/",
    { exact: false }
  )
  .add(
    "/api/latest/hyperfunctions/counter_aggs/",
    "https://docs.timescale.com/api/latest/hyperfunctions/counters-and-gauges/counter_agg/",
    { exact: false }
  )
  .add(
    "/api/latest/hyperfunctions/downsample/",
    "https://docs.timescale.com/api/latest/hyperfunctions/downsampling",
    { exact: false }
  )
  .add(
    "/api/latest/hyperfunctions/frequency-analysis/duration_in",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/duration_in/"
  )
  .add(
    "/api/latest/hyperfunctions/frequency-analysis/interpolated_duration_in",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/interpolated_duration_in/"
  )
  .add(
    "/api/latest/hyperfunctions/frequency-analysis/into_values-state_agg",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/into_values-state_agg/"
  )
  .add(
    "/api/latest/hyperfunctions/frequency-analysis/state_agg",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-aggregates/state_agg/"
  )
  .add(
    "/api/latest/hyperfunctions/percentile-approximation/num_vals/",
    "https://docs.timescale.com/api/latest/hyperfunctions/percentile-approximation/num_vals-percentile/"
  )
  .add(
    "/api/latest/hyperfunctions/state-aggregates/",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-tracking/state_agg/",
    { exact: false }
  )
  .add(
    "/api/latest/hyperfunctions/state-tracking/timeline_agg",
    "https://docs.timescale.com/api/latest/hyperfunctions/state-tracking/state_agg/"
  )
  .add(
    "/api/latest/hyperfunctions/statistical-aggregates",
    "https://docs.timescale.com/api/latest/hyperfunctions/statistical-and-regression-analysis/stats_agg-one-variable",
    { exact: false }
  )
  .add(
    "/api/latest/hyperfunctions/time-weighted-averages",
    "https://docs.timescale.com/api/latest/hyperfunctions/time-weighted-calculations/time_weight",
    { exact: false }
  )
  .add("cloud", "https://docs.timescale.com/cloud/latest/")
  .add(
    "/cloud/latest/account-management",
    "https://docs.timescale.com/cloud/latest/billing/"
  )
  .add(
    "/cloud/latest/backup-restore-cloud.md/",
    "https://docs.timescale.com/cloud/latest/backup-restore-cloud/"
  )
  .add(
    "/cloud/latest/create-a-service",
    "https://docs.timescale.com/cloud/latest/services/"
  )
  .add(
    "/cloud/latest/customize-configuration",
    "https://docs.timescale.com/cloud/latest/service-settings/"
  )
  .add(
    "/cloud/latest/disk-management",
    "https://docs.timescale.com/cloud/latest/service-operations/resources"
  )
  .add(
    "/cloud/latest/explorer",
    "https://docs.timescale.com/cloud/latest/service-explorer"
  )
  .add(
    "/cloud/latest/maintenance",
    "https://docs.timescale.com/cloud/latest/service-operations/maintenance"
  )
  .add(
    "/cloud/latest/memory-management",
    "https://docs.timescale.com/cloud/latest/service-operations/resources"
  )
  .add(
    "/cloud/latest/metrics",
    "https://docs.timescale.com/cloud/latest/service-metric"
  )
  .add(
    "/cloud/latest/operations",
    "https://docs.timescale.com/cloud/latest/service-operations/"
  )
  .add(
    "/cloud/latest/scaling-a-service",
    "https://docs.timescale.com/cloud/latest/service-operations/autoscaling"
  )
  .add(
    "/cloud/latest/service-operations/general",
    "https://docs.timescale.com/cloud/latest/service-operations/service-management"
  )
  .add(
    "/cloud/latest/service-settings/",
    "https://docs.timescale.com/cloud/latest/service-operations/database-parameters/"
  )
  .add(
    "/cloud/latest/service-settings/customize-configuration",
    "https://docs.timescale.com/cloud/latest/service-operations/database-parameters/customize-configuration/"
  )
  .add(
    "/cloud/latest/service-settings/settings-advanced",
    "https://docs.timescale.com/cloud/latest/service-operations/database-parameters/advanced-parameters/"
  )
  .add(
    "/cloud/latest/user-management",
    "https://docs.timescale.com/cloud/latest/members/"
  )
  .add(
    "/cloud/latest/vpc-peering",
    "https://docs.timescale.com/cloud/latest/service-operations/vpc"
  )
  .add(
    "/clustering/getting-started/scaling-out/",
    "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
  )
  .add(
    "/clustering/introduction/architecture/",
    "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
  )
  .add(
    "/clustering/tutorials/clustering/",
    "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/"
  )
  .add(
    "development",
    "https://docs.timescale.com/timescaledb/latest/contribute-to-timescaledb/"
  )
  .add(
    "/development/contribute-to-docs",
    "https://docs.timescale.com/timescaledb/latest/contribute-to-docs/"
  )
  .add(
    "/distributed-hypertables/add_data_node/",
    "https://docs.timescale.com/api/latest/distributed-hypertables/add_data_node/"
  )
  .add("/faq", "https://docs.timescale.com/timescaledb/latest/overview/faq/")
  .add(
    "/forge/getting-started-forge/",
    "https://docs.timescale.com/cloud/latest/create-a-service/"
  )
  .add("/forge", "https://docs.timescale.com/cloud/latest/")
  .add("/getting-started", "https://docs.timescale.com/getting-started/latest/")
  .add(
    "/getting-started/configuring",
    "https://docs.timescale.com/timescaledb/latest/administration/configuration/"
  )
  .add(
    "/getting-started/creating-hypertables",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
  )
  .add(
    "/getting-started/exploring-cloud",
    "https://docs.timescale.com/mst/latest/about-mst/"
  )
  .add(
    "/getting-started/exploring-cloud/cloud-multi-node",
    "https://docs.timescale.com/mst/latest/mst-multi-node/"
  )
  .add(
    "/getting-started/exploring-forge",
    "https://docs.timescale.com/cloud/latest/create-a-service/"
  )
  .add(
    "/getting-started/exploring-forge/forge-configuration",
    "https://docs.timescale.com/cloud/latest/service-operations/database-parameters/"
  )
  .add(
    "/getting-started/exploring-forge/forge-multi-node",
    "https://docs.timescale.com/cloud/latest/cloud-multi-node/"
  )
  .add(
    "/getting-started/exploring-forge/forge-resize",
    "https://docs.timescale.com/cloud/latest/scaling-a-service/"
  )
  .add(
    "/getting-started/install-psql-tutorial",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/psql/"
  )
  .add(
    "/getting-started/installation",
    "https://docs.timescale.com/install/latest/"
  )
  .add(
    "/getting-started/installation/ami/installation-ubuntu-ami",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/getting-started/installation/azure/installation-windows-azure",
    "https://docs.timescale.com/install/latest/installation-mst/"
  )
  .add(
    "/getting-started/installation/debian/installation-apt-debian",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/getting-started/installation/debian/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/getting-started/installation/docker/installation-docker",
    "https://docs.timescale.com/install/latest/installation-docker/"
  )
  .add(
    "/getting-started/installation/macos/installation-homebrew",
    "https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
  )
  .add(
    "/getting-started/installation/macos/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
  )
  .add(
    "/getting-started/installation/rhel-centos/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
  )
  .add(
    "/getting-started/installation/rhel-centos/installation-yum",
    "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
  )
  .add(
    "/getting-started/installation/timescale-cloud/installation-timescale-cloud",
    "https://docs.timescale.com/install/latest/installation-mst/"
  )
  .add(
    "/getting-started/installation/timescale-forge/installation-timescale-forge",
    "https://docs.timescale.com/install/latest/installation-cloud/"
  )
  .add(
    "/getting-started/installation/ubuntu/installation-apt-ubuntu",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/getting-started/installation/ubuntu/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/getting-started/installation/windows/",
    "https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
    { exact: false }
  )
  .add(
    "/getting-started/installation-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/installation/"
  )
  .add(
    "/getting-started/migrating-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/"
  )
  .add("/getting-started/setup", "https://docs.timescale.com/install/latest/")
  .add(
    "/getting-started/setup-multi-node-basic",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
  )
  .add(
    "/getting-started/setup-multi-node-basic/multi-node-self-managed",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
  )
  .add(
    "/introduction",
    "https://docs.timescale.com/timescaledb/latest/overview/"
  )
  .add(
    "/introduction/architecture",
    "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/"
  )
  .add(
    "/introduction/data-model",
    "https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/"
  )
  .add(
    "/introduction/time-series-data",
    "https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/"
  )
  .add(
    "/introduction/timescaledb-vs-nosql/",
    "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/"
  )
  .add(
    "/introduction/timescaledb-vs-postgres",
    "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/"
  )
  .add("/latest/", "https://docs.timescale.com/timescaledb/latest/")
  .add(
    "/latest/administration/configuration",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/about-configuration"
  )
  .add(
    "/latest/administration/telemetry",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
  )
  .add("/latest/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add(
    "/latest/api/api-timescaledb/",
    "https://docs.timescale.com/api/latest/",
    { exact: false, appendPath: true }
  )
  .add(
    "/latest/development",
    "https://docs.timescale.com/timescaledb/latest/contribute-to-timescaledb/"
  )
  .add(
    "/latest/development/contribute-to-docs",
    "https://docs.timescale.com/timescaledb/latest/contribute-to-docs/"
  )
  .add(
    "/latest/faq",
    "https://docs.timescale.com/timescaledb/latest/overview/faq/",
    { exact: false }
  )
  .add(
    "/latest/getting-started/",
    "https://docs.timescale.com/getting-started/latest/"
  )
  .add(
    "/latest/getting-started/configuring",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/"
  )
  .add(
    "/latest/getting-started/create-hypertable/",
    "https://docs.timescale.com/getting-started/latest/create-hypertable/"
  )
  .add(
    "/latest/getting-started/creating-hypertables",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/"
  )
  .add(
    "/latest/getting-started/exploring-cloud",
    "https://docs.timescale.com/cloud/latest/customize-configuration/"
  )
  .add(
    "/latest/getting-started/exploring-cloud/cloud-multi-node",
    "https://docs.timescale.com/cloud/latest/customize-configuration/"
  )
  .add(
    "/latest/getting-started/exploring-forge",
    "https://docs.timescale.com/cloud/latest/create-a-service/"
  )
  .add(
    "/latest/getting-started/exploring-forge/forge-multi-node",
    "https://docs.timescale.com/cloud/latest/cloud-multi-node/"
  )
  .add(
    "/latest/getting-started/exploring-forge/forge-resize",
    "https://docs.timescale.com/cloud/latest/scaling-a-service/"
  )
  .add(
    "/latest/getting-started/install-psql-tutorial",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/"
  )
  .add(
    "/latest/getting-started/installation",
    "https://docs.timescale.com/install/latest/"
  )
  .add(
    "/latest/getting-started/installation/ami/installation-ubuntu-ami",
    "https://docs.timescale.com/install/latest/installation-cloud-image/"
  )
  .add(
    "/latest/getting-started/installation/debian/installation-apt-debian",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/latest/getting-started/installation/docker/installation-docker",
    "https://docs.timescale.com/install/latest/installation-docker/"
  )
  .add(
    "/latest/getting-started/installation/debian/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-source/"
  )
  .add(
    "/latest/getting-started/installation/docker/installation-docker",
    "https://docs.timescale.com/install/latest/installation-docker/"
  )
  .add(
    "/latest/getting-started/installation/macos/installation-homebrew",
    "https://docs.timescale.com/install/latest/self-hosted/installation-macos/"
  )
  .add(
    "/latest/getting-started/installation/macos/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-source/"
  )
  .add(
    "/latest/getting-started/installation/rhel-centos/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
  )
  .add(
    "/latest/getting-started/installation/rhel-centos/installation-yum",
    "https://docs.timescale.com/install/latest/self-hosted/installation-redhat/"
  )
  .add(
    "/latest/getting-started/installation/timescale-cloud/",
    "https://docs.timescale.com/install/latest/installation-cloud/"
  )
  .add(
    "/latest/getting-started/installation/timescale-forge/installation-timescale-forge",
    "/install/latest/installation-cloud/"
  )
  .add(
    "/latest/getting-started/installation/ubuntu/installation-apt-ubuntu",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/latest/getting-started/installation/ubuntu/installation-source",
    "https://docs.timescale.com/install/latest/self-hosted/installation-debian/"
  )
  .add(
    "/latest/getting-started/installation/windows/",
    "https://docs.timescale.com/install/latest/self-hosted/installation-windows/",
    { exact: false }
  )
  .add(
    "/latest/getting-started/installation-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/installation/"
  )
  .add(
    "/latest/getting-started/migrating-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/"
  )
  .add(
    "/latest/getting-started/setup-multi-node-basic",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/",
    { exact: false }
  )
  .add(
    "/latest/getting-started/setup",
    "https://docs.timescale.com/install/latest/"
  )
  .add(
    "/latest/how-to-guides/compression/compression",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression"
  )
  .add(
    "/latest/how-to-guides/multi-node-setup/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/"
  )
  .add(
    "/latest/how-to-guides/psql-basics/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/connecting/about-psql/"
  )
  .add(
    "/latest/how-to-guides/replication-and-ha/replication/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/"
  )
  .add(
    "/latest/introduction",
    "https://docs.timescale.com/timescaledb/latest/overview/"
  )
  .add(
    "/latest/introduction/architecture",
    "https://docs.timescale.com/timescaledb/latest/overview/core-concepts/"
  )
  .add(
    "/latest/introduction/data-model",
    "https://docs.timescale.com/timescaledb/latest/overview/data-model-flexibility/"
  )
  .add(
    "/latest/introduction/time-series-data",
    "https://docs.timescale.com/timescaledb/latest/overview/what-is-time-series-data/"
  )
  .add(
    "/latest/introduction/timescaledb-vs-nosql/",
    "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-nosql/"
  )
  .add(
    "/latest/introduction/timescaledb-vs-postgres",
    "https://docs.timescale.com/timescaledb/latest/overview/how-does-it-compare/timescaledb-vs-postgres/"
  )
  .add("/latest/main", "https://docs.timescale.com/timescaledb/latest/")
  .add(
    "/latest/release-notes",
    "https://docs.timescale.com/timescaledb/latest/overview/release-notes/"
  )
  .add(
    "/latest/release-notes/changes-in-timescaledb-2",
    "https://docs.timescale.com/timescaledb/latest/overview/release-notes/changes-in-timescaledb-2/"
  )
  .add(
    "/latest/tutorials",
    "https://docs.timescale.com/timescaledb/latest/tutorials/"
  )
  .add(
    "/latest/tutorials/analyze-cryptocurrency-data",
    "https://docs.timescale.com/timescaledb/latest/tutorials/analyze-cryptocurrency-data/"
  )
  .add(
    "/latest/tutorials/clustering",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
  )
  .add(
    "/latest/tutorials/continuous-aggs-tutorial",
    "https://docs.timescale.com/getting-started/latest/create-cagg/"
  )
  .add(
    "/latest/tutorials/getting-started-with-promscale",
    "https://docs.timescale.com/promscale/latest/",
    { exact: false }
  )
  .add(
    "/latest/tutorials/other-sample-datasets",
    "https://docs.timescale.com/timescaledb/latest/tutorials/sample-datasets/"
  )
  .add(
    "/latest/tutorials/outflux",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/"
  )
  .add(
    "/latest/tutorials/quickstart-go/",
    "https://docs.timescale.com/timescaledb/latest/quick-start/golang/"
  )
  .add(
    "/latest/tutorials/quickstart-node",
    "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/node/"
  )
  .add(
    "/latest/tutorials/quickstart-node/",
    "https://docs.timescale.com/timescaledb/latest/quick-start/node/"
  )
  .add(
    "/latest/tutorials/quickstart-python",
    "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/python/"
  )
  .add(
    "/latest/tutorials/quickstart-python/",
    "https://docs.timescale.com/timescaledb/latest/quick-start/python/"
  )
  .add(
    "/latest/tutorials/quickstart-ruby",
    "https://docs.timescale.com/timescaledb/latest/tutorials/quick-starts/ruby/"
  )
  .add(
    "/latest/tutorials/replication",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/"
  )
  .add(
    "/latest/tutorials/telegraf-output-plugin",
    "https://docs.timescale.com/timescaledb/latest/tutorials/telegraf-output-plugin"
  )
  .add(
    "/latest/tutorials/tutorial-forecasting",
    "https://docs.timescale.com/timescaledb/latest/tutorials/time-series-forecast/"
  )
  .add(
    "/latest/tutorials/tutorial-grafana-alerts",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/setup-alerts/"
  )
  .add(
    "/latest/tutorials/tutorial-grafana-dashboards",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/create-dashboard-and-panel/"
  )
  .add(
    "^/latest/tutorials/tutorial-grafana-geospatial",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/geospatial-dashboards/"
  )
  .add(
    "/latest/tutorials/tutorial-grafana-variables",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/grafana-variables/"
  )
  .add(
    "/latest/tutorials/tutorial-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/"
  )
  .add(
    "/latest/tutorials/tutorial-hello-nyc",
    "https://docs.timescale.com/timescaledb/latest/tutorials/nyc-taxi-cab/"
  )
  .add(
    "/latest/tutorials/tutorial-hello-timescale",
    "https://docs.timescale.com/getting-started/latest/"
  )
  .add(
    "/latest/tutorials/tutorial-howto-monitor-django-prometheus",
    "https://docs.timescale.com/timescaledb/latest/tutorials/howto-monitor-django-prometheus"
  )
  .add(
    "/latest/tutorials/tutorial-howto-simulate-iot-sensor-data",
    "https://docs.timescale.com/timescaledb/latest/tutorials/simulate-iot-sensor-data/"
  )
  .add(
    "/latest/tutorials/tutorial-howto-visualize-missing-data-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/visualize-missing-data/"
  )
  .add(
    "/latest/tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus",
    "https://docs.timescale.com/timescaledb/latest/tutorials/monitor-mst-with-prometheus/"
  )
  .add(
    "/latest/tutorials/tutorial-use-timescale-prometheus-grafana/",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/"
  )
  .add(
    "/latest/tutorials/visualizing-time-series-data-in-tableau",
    "https://docs.timescale.com/timescaledb/latest/tutorials/visualize-with-tableau/"
  )
  .add(
    "/latest/update-timescaledb",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
  )
  .add(
    "/latest/update-timescaledb/update-docker",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/"
  )
  .add(
    "/latest/update-timescaledb/update-tsdb-2",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/"
  )
  .add(
    "/latest/update-timescaledb/upgrade-pg",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/"
  )
  .add(
    "/latest/using-timescaledb",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/",
    { exact: false, appendPath: true }
  )
  .add(
    "/latest/using-timescaledb/actions",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/"
  )
  .add(
    "/latest/using-timescaledb/backup",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/"
  )
  .add(
    "/latest/using-timescaledb/ingesting-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/"
  )
  .add(
    "/latest/using-timescaledb/limitations",
    "https://docs.timescale.com/timescaledb/latest/overview/limitations/"
  )
  .add(
    "/latest/using-timescaledb/reading-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/"
  )
  .add(
    "/latest/using-timescaledb/telemetry",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
  )
  .add(
    "/latest/using-timescaledb/update-db/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
  )
  .add(
    "/latest/using-timescaledb/visualizing-data",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/"
  )
  .add(
    "/latest/using-timescaledb/writing-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/"
  )
  .add("/main", "https://docs.timescale.com/timescaledb/latest/")
  .add(
    "/mst/latest/create-a-service",
    "https://docs.timescale.com/mst/latest/about-mst"
  )
  .add("/mst", "https://docs.timescale.com/mst/latest/")
  .add(
    "/release-notes",
    "https://docs.timescale.com/timescaledb/latest/overview/release-notes/",
    { exact: false, appendPath: true }
  )
  .add("/timescale-cloud", "https://docs.timescale.com/mst/latest/", {
    exact: false,
  })
  .add("/timescale-forge", "https://docs.timescale.com/cloud/latest/", {
    exact: false,
  })
  .add("/timescale-forge/latest", "https://docs.timescale.com/cloud/latest/")
  .add("/timescaledb/", "https://docs.timescale.com/timescaledb/latest/")
  .add("/timescaledb/latest/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add(
    "/timescaledb/latest/getting-started/",
    "https://docs.timescale.com/getting-started/latest/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/compression/compression-basics/",
    "https://docs.timescale.com/latest/how-to-guides/compression/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/continuous-aggregates/adding-automatic-refresh-policies/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/data-tiering",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/manage-storage/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/hypertables/best-practices",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables/#best-practices-for-time-partitioning"
  )
  .add(
    "/timescaledb/latest/how-to-guides/hypertables/distributed-hypertables",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/install-timescaledb-toolkit/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/install-timescaledb/",
    "https://docs.timescale.com/install/latest/"
  )
  .add(
    "/timescaledb/latest/how-to-guides/multi-node-setup/",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/"
  )
  .add(
    "/timescaledb/latest/tutorials/financial-candlestick-tick-data/",
    "https://docs.timescale.com/timescaledb/latest/tutorials/financial-tick-data/"
  )
  .add(
    "/timescaledb/latest/tutorials/howto-monitor-django-prometheus",
    "https://docs.timescale.com/timescaledb/latest/tutorials/monitor-django-with-prometheus/"
  )
  .add(
    "/timescaledb/latest/tutorials/promscale/",
    "https://docs.timescale.com/promscale/latest/"
  )
  .add(
    "/timescaledb/latest/tutorials/setting-up-mst-endpoint-for-prometheus/",
    "https://docs.timescale.com/timescaledb/latest/tutorials/monitor-mst-with-prometheus/"
  )
  .add(
    "/timescaledb/latest/tutorials/",
    "https://docs.timescale.com/timescaledb/latest/tutorials/monitor-mst-with-prometheus/"
  )
  .add(
    "/timescaledb/latest/tutorials/visualize-with-tableu/",
    "https://docs.timescale.com/timescaledb/latest/tutorials/visualize-with-tableau/"
  )
  .add(
    "/tutorials/clustering",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/"
  )
  .add(
    "/tutorials/continuous-aggs-tutorial",
    "https://docs.timescale.com/getting-started/latest/create-cagg/"
  )
  .add(
    "/tutorials/getting-started-with-promscale",
    "https://docs.timescale.com/promscale/latest/",
    { exact: false }
  )
  .add(
    "/tutorials/other-sample-datasets",
    "https://docs.timescale.com/timescaledb/latest/tutorials/sample-datasets/"
  )
  .add(
    "/tutorials/outflux",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/migrate-data/migrate-influxdb/"
  )
  .add(
    "/tutorials/quickstart-go",
    "https://docs.timescale.com/timescaledb/latest/quick-start/golang/"
  )
  .add(
    "/tutorials/quickstart-node",
    "https://docs.timescale.com/timescaledb/latest/quick-start/node/"
  )
  .add(
    "/tutorials/quickstart-python",
    "https://docs.timescale.com/timescaledb/latest/quick-start/python/"
  )
  .add(
    "/tutorials/quickstart-ruby",
    "https://docs.timescale.com/timescaledb/latest/quick-start/ruby/"
  )
  .add(
    "/tutorials/replication",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/"
  )
  .add(
    "/tutorials/telegraf-output-plugin",
    "https://docs.timescale.com/timescaledb/latest/tutorials/telegraf-output-plugin"
  )
  .add(
    "/tutorials/tutorial-forecasting",
    "https://docs.timescale.com/timescaledb/latest/tutorials/time-series-forecast/"
  )
  .add(
    "^/tutorials/tutorial-grafana-alerts",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/setup-alerts/"
  )
  .add(
    "/tutorials/tutorial-grafana-dashboards",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/create-dashboard-and-panel/"
  )
  .add(
    "/tutorials/tutorial-grafana-geospatial",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/geospatial-dashboards/"
  )
  .add(
    "/tutorials/tutorial-grafana-variables",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/grafana-variables/"
  )
  .add(
    "/tutorials/tutorial-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/"
  )
  .add(
    "/tutorials/tutorial-hello-timescale",
    "https://docs.timescale.com/getting-started/latest/"
  )
  .add(
    "/tutorials/tutorial-howto-monitor-django-prometheus",
    "https://docs.timescale.com/timescaledb/latest/tutorials/howto-monitor-django-prometheus"
  )
  .add(
    "/tutorials/tutorial-howto-simulate-iot-sensor-data",
    "https://docs.timescale.com/timescaledb/latest/tutorials/simulate-iot-sensor-data/"
  )
  .add(
    "/tutorials/tutorial-howto-visualize-missing-data-grafana",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/visualize-missing-data/"
  )
  .add(
    "/tutorials/tutorial-setting-up-timescale-cloud-endpoint-for-prometheus",
    "https://docs.timescale.com/timescaledb/latest/tutorials/setting-up-mst-for-prometheus/"
  )
  .add(
    "/tutorials/visualizing-time-series-data-in-tableau",
    "https://docs.timescale.com/timescaledb/latest/tutorials/visualize-with-tableau/"
  )
  .add("/tutorials", "https://docs.timescale.com/timescaledb/latest/tutorials/")
  .add(
    "/update-timescaledb",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
  )
  .add(
    "/update-timescaledb/update-docker",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/"
  )
  .add(
    "/update-timescaledb/update-tsdb-2",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/"
  )
  .add(
    "/update-timescaledb/upgrade-pg",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/"
  )
  .add(
    "/using-timescaledb",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/",
    { exact: false, appendPath: true }
  )
  .add(
    "/using-timescaledb/actions",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/"
  )
  .add(
    "/using-timescaledb/backup",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/"
  )
  .add(
    "/using-timescaledb/ingesting-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/"
  )
  .add(
    "/using-timescaledb/limitations",
    "https://docs.timescale.com/timescaledb/latest/overview/limitations/"
  )
  .add(
    "/using-timescaledb/reading-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/"
  )
  .add(
    "/using-timescaledb/telemetry",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/"
  )
  .add(
    "/using-timescaledb/troubleshooting",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/troubleshoot-timescaledb"
  )
  .add(
    "/using-timescaledb/update-db",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/"
  )
  .add(
    "/using-timescaledb/visualizing-data",
    "https://docs.timescale.com/timescaledb/latest/tutorials/grafana/"
  )
  .add(
    "/using-timescaledb/writing-data",
    "https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/"
  )
  .add("/v0.8/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.8/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.9/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.9/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.10/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.10/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.11/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.11/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.12/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v0.12/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v2.0/", "https://docs.timescale.com/timescaledb/latest/", {
    exact: false,
    appendPath: true,
  })
  .add("/v2.0/api", "https://docs.timescale.com/api/latest/", {
    exact: false,
    appendPath: true,
  });
