module.exports = [
  {
    title: "Promscale",
    filePath: "index.md",
    href: "promscale",
    name: "Promscale",
    pageComponents: ["featured-cards"],
    excerpt:
      "Promscale is the open source observability backend for metrics and traces powered by SQL, built on top of TimescaleDB.",
    children: [
      {
        title: "About Promscale",
        href: "about-promscale",
        tags: ["promscale", "learn", "analytics", "prometheus"],
        keywords: ["Promscale", "analytics"],
        excerpt: "Learn about Promscale and how it works",
      },
      {
        title: "Promscale benefits",
        href: "promscale-benefits",
        tags: ["promscale", "learn", "analytics", "prometheus"],
        keywords: ["Promscale", "analytics"],
        excerpt: "Learn about the benefits of Promscale",
      },
      {
        title: "Install Promscale",
        href: "installation",
        tags: ["promscale", "learn", "analytics", "prometheus"],
        keywords: ["Promscale", "analytics"],
        relatedPages: [
          "/promscale/:currentVersion:/installation/recomm-guide",
          "/promscale/:currentVersion:/send-data/",
        ],
        excerpt:
          "Install Promscale on Kubernetes, Docker, virtual machine, or bare metal",
        children: [
          {
            title: "Install Promscale on Kubernetes",
            href: "kubernetes",
            tags: ["promscale", "install", "kubernetes", "analytics", "helm"],
            keywords: ["Promscale", "Kubernetes", "analytics", "Helm"],
            relatedPages: [
              "/promscale/:currentVersion:/installation/recomm-guide",
              "/promscale/:currentVersion:/send-data/",
            ],
            excerpt: "Install Promscale on a Kubernetes cluster",
          },
          {
            title: "Install Promscale with Docker",
            href: "docker",
            tags: ["promscale", "install", "analytics", "docker"],
            keywords: ["Promscale", "analytics", "Docker"],
            relatedPages: [
              "/promscale/:currentVersion:/installation/recomm-guide",
              "/promscale/:currentVersion:/send-data/",
            ],
            excerpt: "Install Docker for Promscale",
          },
          {
            title: "Install Promscale from source",
            href: "source",
            tags: ["promscale", "install", "analytics"],
            keywords: ["Promscale", "analytics"],
            relatedPages: [
              "/promscale/:currentVersion:/installation/recomm-guide",
              "/promscale/:currentVersion:/send-data/",
            ],
            excerpt: "Install Promscale on bare metal",
          },
          {
            title: "Resource recommendation guide",
            href: "recomm-guide",
            tags: ["promscale", "install", "analytics"],
            keywords: ["Promscale", "analytics"],
            excerpt: "Recommended resources for Promscale",
          },
          {
            title: "Migrate existing data",
            href: "prom-migrator",
            tags: ["promscale", "install", "data", "migration", "prometheus"],
            keywords: ["Promscale", "analytics"],
            excerpt:
              "Use Prom-migrator to send existing Prometheus data to Promscale",
          },
          {
            title: "Install Promscale with tobs",
            href: "tobs",
            tags: ["promscale", "install", "analytics", "k8s"],
            keywords: ["Promscale", "analytics", "Kubernetes,"],
            relatedPages: [
              "/promscale/:currentVersion:/installation/recomm-guide",
              "/promscale/:currentVersion:/send-data/",
            ],
            excerpt: "Install tobs",
          },
        ],
      },
      {
        title: "Send data to Promscale",
        href: "send-data",
        excerpt:
          "Send data to Promscale from Prometheus, OpenTelemetry and other tools",
        children: [
          {
            title: "Prometheus",
            href: "prometheus",
            tags: ["promscale", "configure", "prometheus", "metrics"],
            keywords: ["Promscale", "Prometheus"],
            relatedPages: ["/promscale/:currentVersion:/installation/"],
            excerpt: "Send Prometheus metrics to Promscale",
          },
          {
            title: "OpenTelemetry",
            href: "opentelemetry",
            tags: ["promscale", "configure", "opentelemetry", "traces"],
            keywords: ["Promscale", "OpenTelemetry"],
            excerpt: "Send OpenTelemetry data to Promscale",
          },
        ],
      },
      {
        title: "Query data in Promscale",
        href: "query-data",
        tags: ["promscale", "analytics", "sql", "promql", "prometheus"],
        keywords: ["Promscale", "analytics"],
        excerpt: "Learn how to query data in Promscale",
      },
      {
        title: 'Visualize data in Promscale',
        href: 'visualize-data',
        tags: ['promscale', 'visualization', 'analytics', 'grafana', 'jaeger'],
        keywords: ['Promscale', 'analytics', 'Grafana'],
        excerpt: 'Learn about data visualization tools you can use with Promscale',
        children: [
          {
            title: 'Grafana',
            href: 'grafana',
            tags: ['promscale', 'configure', 'prometheus', 'metrics'],
            keywords: ['Promscale', 'Grafana'],
            excerpt: 'Grafana to visualize data in Promscale',
          },
          {
            title: 'Jaeger',
            href: 'jaeger',
            tags: ['promscale', 'configure', 'jaeger', 'opentelemetry', 'traces'],
            keywords: ['Promscale', 'Jaeger'],
            excerpt: 'Jaeger to visualize data in Promscale',
          },
        ],
      },
      {
        title: "tobs",
        href: "tobs",
        excerpt:
          "Install a complete observability stack in Kubernetes with tobs",
        children: [
          {
            title: "About tobs",
            href: "about",
            tags: ["tobs", "install", "k8s", "monitor", "timescaledb"],
            keywords: [
              "tobs",
              "Kubernetes",
              "install",
              "timescaleDB",
              "Promscale",
            ],
            excerpt: "Install the observability stack for Kubernetes (tobs)",
          },
          {
            title: "Use tobs",
            href: "use",
            tags: ["tobs", "monitor", "k8s", "timescaledb"],
            keywords: ["tobs", "Kubernetes", "timescaleDB", "Promscale"],
            excerpt: "Using the observability suite for Kubernetes (tobs)",
          },
        ],
      },
      {
        title: "Scale Promscale",
        href: "scale-ha",
        excerpt: "Configure Promscale for scaling and high availability",
        children: [
          {
            title: "Prometheus High availability",
            href: "high-availability",
            tags: ["promscale", "ha", "timescaledb"],
            keywords: ["promscale", "HA", "prometheus", "timescaledb"],
            excerpt: "Configure Promscale and Prometheus high availability",
          },
          {
            title: "Multi-node",
            href: "multi-node",
            tags: ["promscale", "multi-node", "scale", "timescaledb"],
            keywords: ["promscale", "multinode", "scale", "timescaledb"],
            excerpt: "Scale Promscale with a TimescaleDB multinode database",
          },
          {
            title: "Prometheus multi-tenancy",
            href: "prometheus-multi-tenancy",
            tags: [
              "promscale",
              "multi-tenancy",
              "scale",
              "prometheus",
              "timescaledb",
            ],
            keywords: [
              "promscale",
              "multi-tenancy",
              "scale",
              "prometheus",
              "timescaledb",
            ],
            excerpt: "Configure Promscale multi-tenancy for Prometheus",
          },
          {
            title: 'Jaeger',
            href: 'jaeger',
            tags: ['promscale', 'configure', 'jaeger', 'traces'],
            keywords: ['Promscale', 'Jaeger'],
            excerpt: 'Send Jaeger traces to Promscale',
          },
          {
            title: 'Zipkin',
            href: 'zipkin',
            tags: ['promscale', 'configure', 'zipkin', 'traces'],
            keywords: ['Promscale', 'Zipkin'],
            excerpt: 'Send Zipkin traces to Promscale',
          }
        ],
      },
      {
        title: "Monitoring Promscale",
        href: "monitoring-promscale",
        tags: ["promscale", "prometheus", "alert"],
        keywords: ["Promscale", "Prometheus", "alert", "Alert Manager"],
        excerpt: "Learn about how to monitor Promscale",
      },
      {
        title: 'Manage data in Promscale',
        href: 'manage-data',
        excerpt: 'Manage the data stored in Promscale',
        children: [
          {
            title: 'Retention',
            href: 'retention',
            tags: ['promscale', 'configure', 'retention', 'metrics', 'storage'],
            keywords: ['Promscale', 'retention'],
            excerpt: 'Configure data retention policies in Promscale',
          },
          {
            title: 'Downsampling',
            href: 'downsampling',
            tags: ['promscale', 'downsample', 'continuous aggregates', 'metrics', 'recording rules'],
            keywords: ['Promscale', 'Prometheus', 'downsampling'],
            excerpt: 'Configure downsampling in Promscale',
          },
          {
            title: 'Compression',
            href: 'compression',
            tags: ['promscale', 'configure', 'compression', 'metrics', 'storage'],
            keywords: ['Promscale', 'compression'],
            excerpt: 'Configure data compression in Promscale',
          },
          {
            title: 'Delete data',
            href: 'delete-data',
            tags: ['promscale', 'delete', 'metrics'],
            keywords: ['Promscale', 'Prometheus', 'delete'],
            excerpt: 'Delete data in Promscale',
          },
        ],
      },
      {
        title: "Distributed tracing with Promscale",
        href: "distributed-tracing",
        tags: ["promscale", "tracing", "opentelemetry", "jaeger", "grafana"],
        keywords: ["Promscale", "opentelemetry", "tracing", "jaeger"],
        excerpt:
          "Use Promscale for troubleshooting applications with distributed tracing",
      },
      {
        title: "Alert in Promscale",
        href: "alert",
        tags: ["promscale", "prometheus", "alert"],
        keywords: ["Promscale", "Prometheus", "alert", "Alert Manager"],
        excerpt: "Learn about configuring alerts on Promscale data",
      },
      {
        title: "Database roles and permissions",
        href: "roles-and-permissions",
        tags: ["promscale", "roles", "permissions", "database"],
        keywords: ["Promscale", "analytics", "permissions", "roles"],
        excerpt:
          "Learn about the different database roles and permissions Promscale defines",
      },
      {
        title: "Troubleshooting Promscale",
        href: "troubleshooting",
        tags: ["promscale", "learn", "troubleshooting", "prometheus"],
        keywords: ["Promscale", "troubleshooting"],
        excerpt: "Troubleshooting Promscale",
      },
      {
        title: "Promscale CLI reference",
        href: "cli",
        tags: ["promscale", "cli", "reference"],
        keywords: ["Promscale", "cli"],
        excerpt: "Learn about all parameters accepted by the Promscale CLI",
      },
      {
        title: "SQL API reference",
        href: "sql-api",
        tags: ["promscale", "sql", "api", "reference"],
        keywords: ["Promscale", "sql", "api"],
        excerpt: "Learn about all Promscale SQL API functions",
      },
    ],
  },
];
