extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
indicators:
  - ":"
exceptions:
  - API
  - AWS
  - Azure
  - CentOS
  - CLI
  - Cloud
  - Code
  - Cosmos
  - DBeaver
  - Debian
  - Docker
  - Emmet
  - Go
  - Grafana
  - gRPC
  - Hat
  - HNSW
  - Homebrew
  - I
  - InfluxDB
  - Java
  - JavaScript
  - Kubernetes
  - Lambda
  - Linux
  - macOS
  - MacPorts
  - Managed
  - Marketplace
  - MongoDB
  - Node
  - NFT
  - pgAdmin
  - PgVectorizer
  - PostgreSQL
  - Prometheus
  - Promscale
  - Promscale Connector
  - Python
  - qStudio
  - Red
  - REPL
  - Ruby
  - Service
  - Studio
  - SQL
  - Tableau
  - Telegraf
  - Timescale
  - TimescaleDB
  - Toolkit
  - TypeScript
  - Ubuntu
  - URLs
  - Vector
  - Visual
  - VPC
  - VS
  - Windows
