extends: conditional
message: "Remember to include the link."
level: error
scope: raw
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '(\[[^\]]+\](?![\(\[]))'
second: '(\[[^\]]+\](?!\()): \S+'
