extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://developers.google.com/style/word-list"
level: warning
ignorecase: false
action:
  name: replace
swap:
  "(?:BAK| bak)": .bak
  "(?:CSV| csv)": .csv
  "(?:drop ?down) menu": drop-down menu
  "(?:e-mail|Email|E-mail)": email
  "(?:file ?path|path ?name)": path
  "(?:kill|terminate|abort)": stop|exit|cancel|end
  "(?:OAuth ?2|Oauth)": OAuth 2.0
  "(?:ok|Okay)": OK|okay
  "(?:PDF| pdf)": .pdf
  "(?:WiFi|wifi)": Wi-Fi
  "[Mm]ultinode": multi-node
  "Write[- ]Ahead Log": write-ahead log
  '3\-D': 3D
  a SQL: an SQL
  account name: username
  admin: administrator
  Ajax: AJAX
  approx\.: approximately
  autoupdate: automatically update
  check box: checkbox
  CLI: command-line tool
  click on: click|click in
  data are: data is
  data set: dataset
  disabled?: turn off|off
  fewer data: less data
  file name: filename
  firewalls: firewall rules
  functionality: capability|feature
  grayed-out: unavailable
  HTTPs: HTTPS
  Hypershit: Hypershift
  hypershit: hypershift
  in order to: to
  k8s: Kubernetes
  login to: log in to
  master: primary
  network IP address: internal IP address
  open-source: open source
  Postgres: PostgreSQL
  Promscale connector: Promscale Connector
  quickstart: quick start
  regex: regular expression
  SHA1: SHA-1|HAS-SHA1
  sign into: sign in to
  slave: secondary
  static IP address: static external IP address
  time weighted: time-weighted
  url: URL
  user defined actions: user-defined actions
  vanilla: regular|standard
  vs\.: versus
  World Wide Web: web
