name: Check all Markdown links daily

on:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: read
  issues: write

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check links
        uses: tcort/github-action-markdown-link-check@v1.0.16
        id: linkcheck
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: "mlc_config.json"

      - name: Create issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/broken_link_report.md
