name: PR preview cleanup

on:
  pull_request:
    types: [closed]

jobs:
  remove-preview:
    runs-on: ubuntu-latest
    name: Remove preview
    steps:
      - name: Set variables
        id: timescale
        run: |
          echo "DEV_FOLDER=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_OUTPUT
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          repository: timescale/web-documentation
          event-type: remove-docs-content
          client-payload: '{"branch": "${{ steps.timescale.outputs.DEV_FOLDER }}", "pr_number": "${{ env.PR_NUMBER }}"}'
