name: Deploy docs to prod

on:
  push:
    branches:
      - latest

permissions: {}

jobs:
  trigger:
    name: Docs prod deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
        with:
          token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          repository: timescale/web-documentation
          event-type: build-docs-content-prod
