name: Deploy docs to prod

on:
  push:
    branches:
      - latest

permissions: {}

jobs:
  trigger:
    name: Docs prod deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@b8601598d81a169e6e83657904679c500a0af9b8
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: timescale/web-documentation
          event-type: build-docs-content-prod
