name: Deploy redirects to lambda
on:
  push:
    paths:
      - lambda/**

permissions: {}

jobs:
  trigger:
    name: Update changed lambda redirects
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
          repository: timescale/web-documentation
          event-type: build-lambda
          client-payload: '{ "branch": "${{ github.ref_name }}" }'
