name: Deploy docs to prod

on:
  push:
    branches:
      - latest

permissions: {}

jobs:
  trigger:
    name: Docs prod deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: timescale/web-documentation
          event-type: build-docs-content-prod
