name: Deploy docs to prod

on:
  push:
    branches:
      - latest

permissions: {}

jobs:
  trigger:
    name: Docs prod deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@f2696244ec00ed5c659a5cc77f7138ad0302dffb
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: timescale/web-documentation
          event-type: build-docs-content-prod
