name: Check all links on push to launch branch

on:
  push:
    branches:
      - dev-launch-cloud-centric-phase-1

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: "mlc_config.json"
