name: Linting

on: pull_request

permissions:
  contents: read

jobs:
  prose:
    if: github.repository == 'timescale/docs'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run Vale
        uses: errata-ai/vale-action@v2.1.0
        with:
          files: |
            _partials
            _troubleshooting
            about
            api
            getting-started
            mst
            navigation
            quick-start
            self-hosted
            tutorials
            use-timescale
            ai
          reporter: github-pr-review
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

